---
version: "3.6"
services:
  es_server:
    image: es_server
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      MYSQL_HOST: es_database
      MYSQL_USER: engelsystem
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: engelsystem
    #ports:
    #  - "5080:80"
    env_file: .env
    depends_on:
      - es_database
  es_database:
    image: mariadb
    environment:
      MYSQL_DATABASE: engelsystem
      MYSQL_USER: engelsystem
      MYSQL_PASSWORD: engelsystem
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    volumes:
      - db:/var/lib/mysql

